version: '2'

services:
  nginx:
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/overwall/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - shadowsocks
      - nginx-proxy
    networks:
      - proxy

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "127.0.0.1:2080:80"
      - "127.0.0.1:2443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - dhparam:/etc/nginx/dhparam
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  v2fly:
    image: v2fly/v2fly-core:latest
    container_name: v2fly
    restart: always
    volumes:
      - /data/overwall/https/certs:/certs
      - /data/overwall/v2ray/config.json:/etc/v2ray/config.json
    environment:
      VIRTUAL_PORT: "12345"
      HTTPS_METHOD: redirect
    env_file:
      - ./.v2ray.env
    expose:
      - "12345"
    ports:
      - "127.0.0.1:12345:12345"
    networks:
      - proxy

  shadowsocks:
    image: teddysun/shadowsocks-libev:latest
    container_name: shadowsocks
    restart: always
    volumes:
      - /data/overwall/shadowsocks/:/etc/shadowsocks-libev
    expose:
      - "443"
      - "443/udp"
    ports:
      - "127.0.0.1:1443:443"
    networks:
      - proxy

volumes:
  html:
  conf:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/data/overwall/https/conf'
  vhost:
  dhparam:
  certs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/data/overwall/https/certs'

networks:
  proxy:
    external:
      name: nginx-proxy